{
 "title": "Jupyterhub Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Single User Spawn Counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (server_spawn_duration_seconds_count)\n",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Servers Spawn Failure",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(server_spawn_duration_seconds_bucket{status=\"failure\"} [5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "NFS Volume Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(1, node_filesystem_size_bytes{mountpoint=~\"/rootfs/mnt/.*\", fstype=~\"nfs.*\"} - node_filesystem_free_bytes{mountpoint=\"/rootfs/mnt/jhvolume\", fstype=~\"nfs.*\"})",
     "legendFormat": "Total GiB Used {{ mountpoint }}"
    },
    {
     "expr": "topk(1,node_filesystem_size_bytes{mountpoint=~\"/rootfs/mnt/.*\", fstype=~\"nfs.*\"}) ",
     "legendFormat": "Total GiB Size {{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Servers Spawn Time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(server_spawn_duration_seconds_bucket{status=\"success\"} [5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 18 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "topk(1, node_filesystem_free_bytes{mountpoint=\"/rootfs/mnt/jhvolume\",fstype=\"nfs4\"}) * 100 / topk(1,node_filesystem_size_bytes{mountpoint=\"/rootfs/mnt/jhvolume\",fstype=\"nfs4\"})"
    }
   ]
  },
  {
   "title": "Total NFS Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{mountpoint=~\"/rootfs/mnt/.*\", fstype=~\"nfs.*\"})"
    }
   ]
  }
 ]
}